// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaToPizza.Data;

#nullable disable

namespace PizzaToPizza.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418224508_AddUserRole")]
    partial class AddUserRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PizzaToPizza.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Special"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Spicy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sweet"
                        });
                });

            modelBuilder.Entity("PizzaToPizza.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaToPizza.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrderId");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Tomato, mozzarella, basil",
                            Name = "Margherita",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Tomato, mozzarella, pepperoni",
                            Name = "Pepperoni",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Mozzarella, gorgonzola, parmesan, ricotta",
                            Name = "Four Cheese",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Chicken, BBQ sauce, onions, mozzarella",
                            Name = "BBQ Chicken",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Ham, pineapple, mozzarella",
                            Name = "Hawaiian",
                            Price = 9.49m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Tomato, peppers, mushrooms, olives",
                            Name = "Veggie Delight",
                            Price = 8.49m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Spicy salami, tomato, mozzarella, chili flakes",
                            Name = "Diavola",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Jalapeños, beef, onions, mozzarella",
                            Name = "Mexican Heat",
                            Price = 10.49m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Extra chili, pepperoni, hot sauce",
                            Name = "Inferno",
                            Price = 11.49m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Nutella spread, strawberries, powdered sugar",
                            Name = "Nutella Pizza",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Apple slices, cinnamon, cream cheese",
                            Name = "Apple Cinnamon",
                            Price = 8.49m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Banana, caramel sauce, mascarpone",
                            Name = "Banana Caramel",
                            Price = 8.99m
                        });
                });

            modelBuilder.Entity("PizzaToPizza.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PizzaToPizza.Models.Order", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PizzaToPizza.Models.Pizza", b =>
                {
                    b.HasOne("PizzaToPizza.Models.Category", "Category")
                        .WithMany("Pizzas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaToPizza.Models.Order", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("OrderId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PizzaToPizza.Models.Category", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("PizzaToPizza.Models.Order", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
